### PR TITLE
Added Singularity definition file and the documentation.

### LINKED ISSUE #99: Singularity definition file
Hi, I've written a Singularity definition file for BIDScoin. One still has to use `exec` command to run bidsmapper and bidscoiner. I may iterate over it but I thought I can already share it here. Is this of interest?
```
Bootstrap: debootstrap 
MirrorURL: http://deb.debian.org/debian
OSVersion: testing # Needed for newer versions of packages for BIDScoin.

%labels
    Author mateusz.pawlik@sbg.ac.at
    Version v0.0.1

%post
    # Change apt servers
    echo 'deb http://ftp.at.debian.org/debian unstable main' > /etc/apt/sources.list
    
    # Update apt
    apt-get -y update
    
    # Install the latest dcm2niix from sources
    apt-get -y install git build-essential cmake
    git clone https://github.com/rordenlab/dcm2niix.git
    cd dcm2niix
    mkdir build && cd build
    cmake ..
    make install

    # Install BIDScoin from Python repository.
    # NOTE: There were dependency issues. It helped to install PyQt5 from Debian package. 
    apt-get -y install \
        python3-pandas \
        python3-matplotlib \
        python3-numpy \
        python3-pyqt5 \
        python3-ruamel.yaml \
        python3-coloredlogs \
        python3-dateutil \
        python3-nibabel \
        python3-pip
    pip3 install multiecho pydeface drmaa pydicom --upgrade
    pip3 install bidscoin --no-deps # Install as much as possible as Debian package.

    # Fix for running image on ContOS 7 (mri.ccns.sbg.ac.at)
    # The problem may be Linux kernel older than 3.15.
    #   (Answer #3) https://answers.launchpad.net/yade/+question/696260/
    #   https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4497
    #   https://stackoverflow.com/questions/58912268/singularity-container-python-pytorch-why-does-import-torch-work-on-arch-l
    strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
```

### PR DESCRIPTION
**Pull request by mateuszpawlik**
Closes #99

I wasn't sure where to add the documentation and if it's enough.

I also didn't know if there are any tests and how to execute them. There is the `bidscoin -t` option but not in the 3.6.3 version available in pip.

There is no contributing guideline. I tried my best ;-)

### CODE REVIEW

**Comment by marcelzwiers** [comment]
The `dcm2bidsmap` and the `dcm2niix2bids` plugins have been merged (see the [changelog](https://bidscoin.readthedocs.io/en/latest/CHANGELOG.html)), so the real reason was stated in the line above it, i.e. `Plugin ../dcm2niix2bids.py' does not contain ('bidsmapper_plugin',) functions`. I don't understand how you got it to work by adding `dcm2bidsmap` in your template (as that plugin no longer exists)? 

Checks on the bidsmap are always performed when it is loaded, but I have never written formal schemas, so there is certainly room for improvement here. Also, the messages could be improved (the warning was wrong), I will work on it a bit more, thanks for your feedback and thinking along 👍

**Comment by civier** [comment]
Hi  @marcelzwiers

This is Oren Civier from SOVABIDS.
I had the same issue with 
"ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory"
on various Debian-based systems (when building a BIDScoin container for Neurodesk: https://neurodesk.github.io/)
and could solve it as well with running "apt-get install -y python3-pyqt5" before installing bidscoin.

Maybe you can add this dependency to the pip install somehow? Best if you can let me know when done so I can update our container recipe here: https://github.com/NeuroDesk/neurocontainers/blob/master/recipes/bidscoin/build.sh

Best,
Oren

P.S.
I saw that you maintain a Singularity image for BIDScoin, but unfortunately, it requires users to type a long command to execute, e.g.
`singularity exec --bind /my/data:/mnt bidscoin.sif bidscoiner`
Neurodesk may allow users to launch tools from a BIDScoin Singularity container by typing 'bidscoiner' only, for example, and also provides standard desktop interface (a graphical VM) that solves many issues that people might have with the graphics. You can check here for a short explanation video:
https://neurodesk.github.io/docs/overview/
Right now I'm adjusting the BIDScoiner Singularity container for Neurodesk myself, but if you want it to be always up-to-date, you might want to build your Singularity container within Neurodesk to begin with. People would still be able to use it outside of Neurodesk, but if they use it inside Neurodesk, they will get all the edit benefits.
Let me know if it's something that you might like to consider.

**Comment by marcelzwiers** [comment]
Hi Oren,

Thanks for your feedback, really useful (and neurodesk looks great!). In the `requirements.txt` I now have `PyQt5>=5.12.1`, but I myself had problems with our old CentOS 7.6 distribution, giving an error on Qt libraries (ImportError: libQt5Core.so.5: cannot open shared object file: No such file or directory). So I downgraded to v5.14 and then I had no problem. Perhaps the same is also be true for Debian, can you confirm that? Then I could of course change the `requirements.txt` field to `PyQt5>=5.12.1,<=5.14`...

I am not a singularity expert (the image was contributed by @mateuszpawlik), but I would be very happy to merge your contributions :-)

**Comment by civier** [comment]
@marcelzwiers OK. I'm testing it right now and will let you know how it goes.

@mateuszpawlik If you're interested to look into Neurodesk as the platform where you develop the Singularity images of BIDScoin, let me know. It entails many advantages that I didn't list like automatic generation of both docker and Singularity images, CI system, and much more.

**Comment by mateuszpawlik** [comment]
@civier, Neurodesk is certainly an interesting project. For me, the Singularity (Apptainer) image was a pragmatic solution. Once I had it, I shared. I haven't focused on usability of it and it is not crucial for me at the moment. I actually keep a [few definition files for BIDScoin](https://frosch.cosy.sbg.ac.at/anc/containers/-/tree/main/bidscoin).

To solve a long command, you could create an alias (you may need to add some directory binding), something like:
```bash
alias bidscoiner="singularity exec /path/to/bidscoin.sif bidscoiner"
```
Moreover, I haven't found a good solution to access multiple software tools from the same image. This is the case of BIDScoin. I looked into [apps](https://apptainer.org/docs/user/main/definition_files.html#app) but wasn't sure if the apps can share software.

> @mateuszpawlik If you're interested to look into Neurodesk as the platform where you develop the Singularity images of BIDScoin, let me know.

In my opinion, there should be one definition file (single source of truth), disregarding how and where you use it. It belongs in the software repository. But I'm not BIDScoin maintainer and it's not my decision to make.

> It entails many advantages that I didn't list like automatic generation of both docker and Singularity images, CI system, and much more.

Can't you do the same on GitHub? You can certainly do it on GitLab.

**Comment by civier** [comment]
Thanks for your reply @mateuszpawlik 
All good points that will give me food for thought. Let me process it and I'll get back to you later on.

Just one quick question: 
Why did you decide to write a Singularity/Apptainer def file rather than a docker recipe? Given that it's trivial to convert a docker container to a Singularity one, wouldn't you be killing two birds with one stone by writing a docker recipe instead?

**Comment by mateuszpawlik** [comment]
> Why did you decide to write a Singularity/Apptainer def file rather than a docker recipe? Given that it's trivial to convert a docker container to a Singularity one, wouldn't you be killing two birds with one stone by writing a docker recipe instead?

Since I'm rather new to all that, I wanted to "master" one technology at a time ;-) I chose singularity because a user doesn't need root access to execute the images which is kind of a requirement at the moment for me. Apptainer can build an image from a Docker image, but it has to be put first into Docker Hub, right? I browsed quickly now and haven't found a different solution. Can you build Apptainer image from a local Docker image or a Dockerfile?

**Comment by marcelzwiers** [comment]
I rebased and optimized your singularity file, hope this works well for you :-):
https://github.com/Donders-Institute/bidscoin/blob/master/apptainer.def

**Comment by mateuszpawlik** [comment]
Looks good :-) If the resulting container is the same as the one from `Dockerfile` some consider maintaining only the `Dockerfile` and hosting the containers on Docker Hub. There's a [list of limitations and differences](https://apptainer.org/docs/user/latest/docker_and_oci.html#differences-and-limitations-vs-docker) that should be considered in such a case.

**Comment by marcelzwiers** [comment]
I made the dockerfile and the apptainer file indeed similar to make maintenance easier. But I think apptainer gives a better user experience (see the new docs), and I only provide the docker for windows users actually (but I can't say that a great solution), and because some people just think it's the way to go:
1) The apptainer has more features, such as a help and a default run command (`bidscoin --help`) that cannot (as far as I see) be made from just a dockerfile
2) Apptainer users would need to be able to download a dockerimage, which means that I have to upload images to dockerhub or so. I might do that, but I'm not thrilled about the idea
3) The apptainer image is much smaller in size

**Comment by mateuszpawlik** [comment]
Fine with me and I like it. It was just a hint. In some environments, like GitLab CI/CD with Docker executor, only Docker images are supported.

**Comment by marcelzwiers** [comment]
FYI, this is how you can add some FSL tools to your container:

```
    # Install the latest miniconda (needed for FSL install). NB: Keep the version the same as the Docker base image (currently Miniconda3-latest == py311)
    mkdir -p /opt/miniconda3
    curl https://repo.anaconda.com/miniconda/Miniconda3-py310_23.11.0-2-Linux-x86_64.sh --output /opt/miniconda3/miniconda.sh
    bash /opt/miniconda3/miniconda.sh -b -u -p /opt/miniconda3
    rm -rf /opt/miniconda3/miniconda.sh
    export PATH=/opt/miniconda3/bin:$PATH

    # Install FSL tools needed for (me)deface and slicereport
    conda config --set channel_priority strict      # Needed for pngappend, see: https://github.com/NeuroDesk/neurocontainers/pull/598
    conda install -c conda-forge -c https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/ fsl-libvis fsl-avwutils fsl-flirt
```

**Comment by mateuszpawlik** [comment]
Thanks. I'm aware of the conda way. Not ideal but at least I can install only a selection. I've tried that with [FSL Flirt and Bet](https://gitlab.com/ccns/neurocog/neurodataops/anc/containers/fsl-bet-flirt).

**Pull request merged**
