### PR TITLE
Catch ValueError if run is not specified by user for new version of addmetadata

### PR DESCRIPTION
**Pull request by smoia**

### CODE REVIEW

**Comment by marcelzwiers** [comment]
I put the run-index code in a try-catch statement, to catch your `None` case + potential other cases. Apparently it didn't evoke a ValueError, aKeyError or a dateutil.parser.ParserError? What error did you get?

**Comment by marcelzwiers** [comment]
Also, I cannot reproduce your error, i.e. it works normally if I remove the `<<1>>` run-index

**Comment by smoia** [comment]
Hey there, this is the error I got:
```
Writing acquisition time data to: /home/nemo/Data/EuskalIBUR/sub-001/ses-03/sub-001_ses-03_scans.tsv
Traceback (most recent call last):
  File "/home/nemo/.local/bin/bidscoiner", line 8, in <module>
    sys.exit(main())
  File "/home/nemo/.local/lib/python3.8/site-packages/bidscoin/bidscoiner.py", line 376, in main
    bidscoiner(rawfolder    = args.sourcefolder,
  File "/home/nemo/.local/lib/python3.8/site-packages/bidscoin/bidscoiner.py", line 203, in bidscoiner
    addmetadata(bidssession, subid, sesid)
  File "/home/nemo/.local/lib/python3.8/site-packages/bidscoin/bidscoiner.py", line 271, in addmetadata
    prevfmap   = bids.get_bidsvalue(fmap, 'run', str(int(runindex) - 1))
ValueError: invalid literal for int() with base 10: ''
```
I don't have the log anymore cause I restarted bidscoin after this change. Once it finishes (might take a day or two), I'll revert version and run it again to reproduce the error and send you all the logs!

**Comment by marcelzwiers** [comment]
I wonder if you were using the latest code, because your ValueError would have been caught there

**Comment by smoia** [comment]
I'm going to try again as soon as it finishes (which is probably in a day or two, I think parallelisation didn't kick in and I have 100 session of 8 tasks each).

**Pull request closed without merging**
